service: whatsapp-notifier
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

functions:
  hello:
    path: src/functions/hello.handler

custom:
    esbuild:
      bundle: true
      minify: false
      sourcemap: true
      exclude: ['aws-sdk']
      target: 'node14'
      define:
        - 'require.resolve': undefined
      platform: 'node'
      concurrency: 10
 

plugins:
  - serverless-esbuild
