service: whatsapp-notifier
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    TWILIO_ACCOUNT_SID: ${self:custom.secrets.TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${self:custom.secrets.TWILIO_AUTH_TOKEN}

functions:
  sendMessage:
    handler: src/functions/sendMessage.handler
    events:
      - http:
          method: POST
          path: /send   

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/whatsapp-notifier-ssm}
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node14'
    define: 
      'require.resolve': undefined
    platform: 'node'
    concurrency: 10
 

plugins:
  - serverless-esbuild
